### ISSUE TITLE
How to get tracking identifiers?

### ISSUE THREAD

**Issue by amity5020** [AutotaskDevelopment/Sample-Code#4]
How can i get tracking identifiers?

**Comment by janderson-autotask** [comment]
Hi Amity5020,
If you are an Autotask PSA user and developing an application for you own purposes, you can setup and user with the API security level and the security tab of the user screen allows you to create a custom tracking identifier that works only for your database. Your Autotask PSA on-line help has information on how to setup users and API users and the documentation on the Web Services API can help given pointers.

If you are a 3rd party vendor that is looking to build integrations to offer/sell to many partners/MSP's, then if you haven't done this yet, go to: https://www.datto.com/developers

and select the JOIN button and fill out the form to start the process to register for the developer program. 3rd party developers will be issued a tracking identifier that will work for all partner/MSP Autotask PSA systems.

I hope that helps point you in a direction.
-johna
